# [[language]]
# name = "javascript"
# formatter = { command = "prettier", args = ["--parser", "typescript"] }
[language-server]
ra-multiplex = { command = "ra-multiplex" }

[[language]]
name = "rust"
language-servers = [ "ra-multiplex" ]
